# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1 # Run npm install
  displayName: 'npm install'
  inputs:
    command: 'custom'
    customCommand: 'install --no-optional'
    workingDir: '$(System.DefaultWorkingDirectory)'

- task: Npm@1 # Run npm run build
  displayName: 'npm run build'
  inputs:
    command: custom
    customCommand: run build

- publish: 'www/' # Publish App artifact
  artifact: 'www'
  displayName: 'Publishing Artifact'